package view;

import java.awt.event.ActionListener;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Lucía Méndez Rodríguez
 */
public class PanelReservas extends javax.swing.JPanel {

    TableRowSorter tablaOrdenada;

    /**
     * Creates new form VistaReservas
     */
    public PanelReservas() {
        initComponents();
        textFieldBuscarReservas.requestFocusInWindow();
        tableReservas.setRowHeight(35);
        tableReservas.setRowMargin(10);
        tablaOrdenada = new TableRowSorter<>(tableReservas.getModel());
        tableReservas.setRowSorter(tablaOrdenada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonEditarReserva = new javax.swing.JButton();
        panelReservas = new javax.swing.JPanel();
        scrollTableReservas = new javax.swing.JScrollPane();
        tableReservas = new javax.swing.JTable();
        titleReservas = new javax.swing.JLabel();
        textFieldBuscarReservas = new javax.swing.JTextField();
        buttonBuscarReservas = new javax.swing.JButton();
        containerInfoReservas = new javax.swing.JPanel();
        labelIDReserva = new javax.swing.JLabel();
        textFieldIDReserva = new javax.swing.JTextField();
        labelNombreRuta = new javax.swing.JLabel();
        textFieldNombreRuta = new javax.swing.JTextField();
        labelClienteRuta = new javax.swing.JLabel();
        textFieldClienteRuta = new javax.swing.JTextField();
        labelEstado = new javax.swing.JLabel();
        textFieldEstado = new javax.swing.JTextField();
        labelNumPersonas = new javax.swing.JLabel();
        textFieldNumPersonas = new javax.swing.JTextField();
        labelDir = new javax.swing.JLabel();
        textFieldFecha = new javax.swing.JTextField();
        labelImporte = new javax.swing.JLabel();
        textFieldImporte = new javax.swing.JTextField();
        JaPanelCardEditarOk = new javax.swing.JPanel();

        buttonEditarReserva.setBackground(new java.awt.Color(0, 154, 167));
        buttonEditarReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonEditarReserva.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditarReserva.setText("Editar");
        buttonEditarReserva.setBorderPainted(false);
        buttonEditarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEditarReserva.setPreferredSize(new java.awt.Dimension(136, 24));
        buttonEditarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarReservaActionPerformed(evt);
            }
        });

        setPreferredSize(new java.awt.Dimension(800, 500));

        panelReservas.setBackground(new java.awt.Color(0, 79, 86));
        panelReservas.setPreferredSize(new java.awt.Dimension(800, 500));

        scrollTableReservas.setMaximumSize(new java.awt.Dimension(0, 0));

        tableReservas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Reserva", "Ruta", "Fecha", "Cliente", "Nº Personas", "Estado", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableReservas.setMaximumSize(new java.awt.Dimension(600, 0));
        tableReservas.setMinimumSize(new java.awt.Dimension(450, 0));
        tableReservas.setRowMargin(20);
        scrollTableReservas.setViewportView(tableReservas);

        titleReservas.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        titleReservas.setForeground(new java.awt.Color(255, 255, 255));
        titleReservas.setText("Gestionar Reservas");

        textFieldBuscarReservas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        textFieldBuscarReservas.setPreferredSize(new java.awt.Dimension(78, 26));
        textFieldBuscarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscarReservasActionPerformed(evt);
            }
        });

        buttonBuscarReservas.setBackground(new java.awt.Color(0, 154, 167));
        buttonBuscarReservas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonBuscarReservas.setForeground(new java.awt.Color(255, 255, 255));
        buttonBuscarReservas.setText("Buscar");
        buttonBuscarReservas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonBuscarReservas.setBorderPainted(false);
        buttonBuscarReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBuscarReservas.setPreferredSize(new java.awt.Dimension(136, 24));
        buttonBuscarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarReservasActionPerformed(evt);
            }
        });

        containerInfoReservas.setBackground(new java.awt.Color(255, 255, 255));
        containerInfoReservas.setPreferredSize(new java.awt.Dimension(582, 140));

        labelIDReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelIDReserva.setForeground(new java.awt.Color(0, 79, 86));
        labelIDReserva.setText("Nº Reserva:");

        textFieldIDReserva.setEditable(false);
        textFieldIDReserva.setMargin(new java.awt.Insets(2, 8, 2, 8));
        textFieldIDReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIDReservaActionPerformed(evt);
            }
        });

        labelNombreRuta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelNombreRuta.setForeground(new java.awt.Color(0, 79, 86));
        labelNombreRuta.setText("Ruta:");

        textFieldNombreRuta.setEditable(false);
        textFieldNombreRuta.setMargin(new java.awt.Insets(2, 8, 2, 8));
        textFieldNombreRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreRutaActionPerformed(evt);
            }
        });

        labelClienteRuta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelClienteRuta.setForeground(new java.awt.Color(0, 79, 86));
        labelClienteRuta.setText("Cliente:");

        textFieldClienteRuta.setEditable(false);
        textFieldClienteRuta.setMargin(new java.awt.Insets(2, 8, 2, 8));

        labelEstado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelEstado.setForeground(new java.awt.Color(0, 79, 86));
        labelEstado.setText("Estado:");

        textFieldEstado.setEditable(false);
        textFieldEstado.setMargin(new java.awt.Insets(2, 8, 2, 8));

        labelNumPersonas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelNumPersonas.setForeground(new java.awt.Color(0, 79, 86));
        labelNumPersonas.setText("Nº Personas:");

        textFieldNumPersonas.setEditable(false);
        textFieldNumPersonas.setMargin(new java.awt.Insets(2, 8, 2, 8));
        textFieldNumPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumPersonasActionPerformed(evt);
            }
        });

        labelDir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelDir.setForeground(new java.awt.Color(0, 79, 86));
        labelDir.setText("Fecha:");

        textFieldFecha.setEditable(false);
        textFieldFecha.setMargin(new java.awt.Insets(2, 8, 2, 8));

        labelImporte.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelImporte.setForeground(new java.awt.Color(0, 79, 86));
        labelImporte.setText("Importe:");

        textFieldImporte.setEditable(false);
        textFieldImporte.setMargin(new java.awt.Insets(2, 8, 2, 8));

        javax.swing.GroupLayout containerInfoReservasLayout = new javax.swing.GroupLayout(containerInfoReservas);
        containerInfoReservas.setLayout(containerInfoReservasLayout);
        containerInfoReservasLayout.setHorizontalGroup(
            containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInfoReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIDReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreRuta)
                    .addComponent(labelDir)
                    .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerInfoReservasLayout.createSequentialGroup()
                        .addComponent(textFieldIDReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(labelClienteRuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldClienteRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerInfoReservasLayout.createSequentialGroup()
                        .addGroup(containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerInfoReservasLayout.createSequentialGroup()
                                .addComponent(textFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelNumPersonas))
                            .addGroup(containerInfoReservasLayout.createSequentialGroup()
                                .addComponent(textFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelImporte)))
                        .addGap(18, 18, 18)
                        .addGroup(containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(textFieldNombreRuta))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        containerInfoReservasLayout.setVerticalGroup(
            containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInfoReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelIDReserva)
                        .addComponent(textFieldIDReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelClienteRuta)
                        .addComponent(textFieldClienteRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerInfoReservasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldNombreRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(containerInfoReservasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNombreRuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addGroup(containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDir)
                    .addGroup(containerInfoReservasLayout.createSequentialGroup()
                        .addGroup(containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumPersonas)
                            .addComponent(textFieldNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerInfoReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEstado)
                            .addComponent(labelImporte)
                            .addComponent(textFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        JaPanelCardEditarOk.setBackground(new java.awt.Color(0, 79, 86));
        JaPanelCardEditarOk.setPreferredSize(new java.awt.Dimension(85, 24));
        JaPanelCardEditarOk.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelReservasLayout = new javax.swing.GroupLayout(panelReservas);
        panelReservas.setLayout(panelReservasLayout);
        panelReservasLayout.setHorizontalGroup(
            panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReservasLayout.createSequentialGroup()
                        .addComponent(scrollTableReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(panelReservasLayout.createSequentialGroup()
                        .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelReservasLayout.createSequentialGroup()
                                .addComponent(titleReservas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                                .addComponent(textFieldBuscarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(containerInfoReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonBuscarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JaPanelCardEditarOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        panelReservasLayout.setVerticalGroup(
            panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservasLayout.createSequentialGroup()
                .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReservasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleReservas))
                    .addGroup(panelReservasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(buttonBuscarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textFieldBuscarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReservasLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(JaPanelCardEditarOk, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelReservasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(containerInfoReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTableReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldBuscarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscarReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscarReservasActionPerformed

    private void buttonBuscarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarReservasActionPerformed

    private void textFieldIDReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIDReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIDReservaActionPerformed

    private void textFieldNumPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNumPersonasActionPerformed

    private void buttonEditarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditarReservaActionPerformed

    private void textFieldNombreRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreRutaActionPerformed


    /**
     * Añade un listener al botón para buscar reservas.
     *
     * @param listener El listener a añadir.
     */
    public void addBuscarReservas(ActionListener listener) {
        buttonBuscarReservas.addActionListener(listener);
    }
/**
 * Aplica un filtro a la tabla de reservas basado en el texto ingresado en el campo de búsqueda.
 * El filtro es insensible a mayúsculas y minúsculas.
 */
public void filtrar() {
    try {
        String filtro = textFieldBuscarReservas.getText().trim();
        RowFilter<DefaultTableModel, Object> rf = RowFilter.regexFilter(
                "(?i)" + Pattern.quote(filtro), 0, 1, 2, 3, 4, 5);
        tablaOrdenada.setRowFilter(rf);
    } catch (PatternSyntaxException e) {
        // Si hay un error en la expresión regular, limpiar el filtro
        tablaOrdenada.setRowFilter(null);
    }
}

/**
 * Detiene el filtro aplicado a la tabla de reservas, mostrando todas las filas.
 */
public void detenerFiltro() {
    tablaOrdenada.setRowFilter(null);
}

    
    //Getters de componentes

    public JTextField getTextFieldClienteRuta() {
        return textFieldClienteRuta;
    }
    
    public JTextField getTextFieldNombreRuta() {
        return textFieldNombreRuta;
    }

    public JTextField getTextFieldEstado() {
        return textFieldEstado;
    }

    public JTextField getTextFieldFecha() {
        return textFieldFecha;
    }

    public JTextField getTextFieldIDReserva() {
        return textFieldIDReserva;
    }

    public JTextField getTextFieldImporte() {
        return textFieldImporte;
    }

    public JTextField getTextFieldNumPersonas() {
        return textFieldNumPersonas;
    }
    
    public JTable getTableReservas() {
        return tableReservas;
    }

    //Getters del texto de los componentes
    public String getStringClienteRuta() {
        return textFieldClienteRuta.getText();
    }

    public String getStringEstado() {
        return textFieldEstado.getText();
    }

    public String getStringFecha() {
        return textFieldFecha.getText();
    }
    

    public String getStringIDReserva() {
        return textFieldIDReserva.getText();
    }

    public String getStringImporte() {
        return textFieldImporte.getText();
    }

    public String getStringNumPersonas() {
        return textFieldNumPersonas.getText();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JaPanelCardEditarOk;
    private javax.swing.JButton buttonBuscarReservas;
    private javax.swing.JButton buttonEditarReserva;
    private javax.swing.JPanel containerInfoReservas;
    private javax.swing.JLabel labelClienteRuta;
    private javax.swing.JLabel labelDir;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelIDReserva;
    private javax.swing.JLabel labelImporte;
    private javax.swing.JLabel labelNombreRuta;
    private javax.swing.JLabel labelNumPersonas;
    private javax.swing.JPanel panelReservas;
    private javax.swing.JScrollPane scrollTableReservas;
    protected javax.swing.JTable tableReservas;
    private javax.swing.JTextField textFieldBuscarReservas;
    public javax.swing.JTextField textFieldClienteRuta;
    public javax.swing.JTextField textFieldEstado;
    public javax.swing.JTextField textFieldFecha;
    public javax.swing.JTextField textFieldIDReserva;
    public javax.swing.JTextField textFieldImporte;
    public javax.swing.JTextField textFieldNombreRuta;
    public javax.swing.JTextField textFieldNumPersonas;
    private javax.swing.JLabel titleReservas;
    // End of variables declaration//GEN-END:variables
}
