package view;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Lucía Méndez Rodríguez
 */
public class Vista extends javax.swing.JFrame {
    Image icon;
    JPanel panelActual = null;
    
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Galicia Secreta");
        icon = new ImageIcon(getClass().getResource("/img/favicon.png")).getImage();
        setIconImage(icon);
        Image scaledIcon = icon.getScaledInstance(jLabelLogo.getWidth(), jLabelLogo.getHeight(), Image.SCALE_SMOOTH);
        jLabelLogo.setIcon(new ImageIcon(scaledIcon));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelClientes = new javax.swing.JPanel();
        titleClientes = new javax.swing.JLabel();
        textFieldBuscarCliente = new javax.swing.JTextField();
        buttonBuscarCliente = new javax.swing.JButton();
        containerInfoCliente = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        textFieldID = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        labelApellidos = new javax.swing.JLabel();
        textFieldApellidos = new javax.swing.JTextField();
        labelTlf = new javax.swing.JLabel();
        textFieldTlf = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        labelDir = new javax.swing.JLabel();
        textFieldDir = new javax.swing.JTextField();
        buttonEliminarCliente = new javax.swing.JButton();
        scrollTableClientes = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        buttonAnhadirCliente = new javax.swing.JButton();
        JaPanelCardEditarOk = new javax.swing.JPanel();
        buttonEditarCliente = new javax.swing.JButton();
        buttonOKEditarCliente = new javax.swing.JButton();
        contenedorApp = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        buttonMenuClientes = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        buttonMenuReservas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        panelClientes.setBackground(new java.awt.Color(0, 79, 86));
        panelClientes.setEnabled(false);
        panelClientes.setFocusCycleRoot(true);

        titleClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        titleClientes.setForeground(new java.awt.Color(255, 255, 255));
        titleClientes.setText("Gestionar Clientes ");

        textFieldBuscarCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        textFieldBuscarCliente.setPreferredSize(new java.awt.Dimension(78, 26));
        textFieldBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscarClienteActionPerformed(evt);
            }
        });

        buttonBuscarCliente.setBackground(new java.awt.Color(0, 154, 167));
        buttonBuscarCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        buttonBuscarCliente.setText("Buscar");
        buttonBuscarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonBuscarCliente.setBorderPainted(false);
        buttonBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBuscarCliente.setPreferredSize(new java.awt.Dimension(136, 24));
        buttonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarClienteActionPerformed(evt);
            }
        });

        containerInfoCliente.setBackground(new java.awt.Color(255, 255, 255));
        containerInfoCliente.setPreferredSize(new java.awt.Dimension(582, 140));

        labelID.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelID.setForeground(new java.awt.Color(0, 79, 86));
        labelID.setText("ID:");

        textFieldID.setEditable(false);
        textFieldID.setMargin(new java.awt.Insets(2, 8, 2, 8));
        textFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIDActionPerformed(evt);
            }
        });

        labelNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(0, 79, 86));
        labelNombre.setText("Nombre:");

        textFieldNombre.setEditable(false);
        textFieldNombre.setMargin(new java.awt.Insets(2, 8, 2, 8));

        labelApellidos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelApellidos.setForeground(new java.awt.Color(0, 79, 86));
        labelApellidos.setText("Apellidos:");

        textFieldApellidos.setEditable(false);
        textFieldApellidos.setMargin(new java.awt.Insets(2, 8, 2, 8));

        labelTlf.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelTlf.setForeground(new java.awt.Color(0, 79, 86));
        labelTlf.setText("Teléfono:");

        textFieldTlf.setEditable(false);
        textFieldTlf.setMargin(new java.awt.Insets(2, 8, 2, 8));

        labelEmail.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 79, 86));
        labelEmail.setText("Email:");

        textFieldEmail.setEditable(false);
        textFieldEmail.setMargin(new java.awt.Insets(2, 8, 2, 8));
        textFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailActionPerformed(evt);
            }
        });

        labelDir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelDir.setForeground(new java.awt.Color(0, 79, 86));
        labelDir.setText("Dirección:");

        textFieldDir.setEditable(false);
        textFieldDir.setMargin(new java.awt.Insets(2, 8, 2, 8));

        javax.swing.GroupLayout containerInfoClienteLayout = new javax.swing.GroupLayout(containerInfoCliente);
        containerInfoCliente.setLayout(containerInfoClienteLayout);
        containerInfoClienteLayout.setHorizontalGroup(
            containerInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInfoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre)
                    .addComponent(labelTlf)
                    .addComponent(labelDir))
                .addGap(18, 18, 18)
                .addGroup(containerInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerInfoClienteLayout.createSequentialGroup()
                        .addGroup(containerInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldTlf)
                            .addComponent(textFieldNombre)
                            .addComponent(textFieldID))
                        .addGap(26, 26, 26)
                        .addGroup(containerInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelApellidos)
                            .addComponent(labelEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldApellidos)
                            .addComponent(textFieldEmail)))
                    .addComponent(textFieldDir))
                .addGap(30, 30, 30))
        );
        containerInfoClienteLayout.setVerticalGroup(
            containerInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInfoClienteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(containerInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApellidos)
                    .addComponent(textFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTlf)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        buttonEliminarCliente.setBackground(new java.awt.Color(153, 0, 0));
        buttonEliminarCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        buttonEliminarCliente.setText("Eliminar Cliente");
        buttonEliminarCliente.setBorderPainted(false);
        buttonEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarClienteActionPerformed(evt);
            }
        });

        scrollTableClientes.setMaximumSize(new java.awt.Dimension(0, 0));

        tableClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento Id", "Nombre", "Apellidos", "Teléfono", "Email", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableClientes.setMaximumSize(new java.awt.Dimension(600, 0));
        tableClientes.setMinimumSize(new java.awt.Dimension(450, 0));
        scrollTableClientes.setViewportView(tableClientes);

        buttonAnhadirCliente.setBackground(new java.awt.Color(0, 154, 167));
        buttonAnhadirCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonAnhadirCliente.setForeground(new java.awt.Color(255, 255, 255));
        buttonAnhadirCliente.setText("Añadir");
        buttonAnhadirCliente.setBorderPainted(false);
        buttonAnhadirCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonAnhadirCliente.setPreferredSize(new java.awt.Dimension(136, 24));
        buttonAnhadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnhadirClienteActionPerformed(evt);
            }
        });

        JaPanelCardEditarOk.setBackground(new java.awt.Color(0, 79, 86));
        JaPanelCardEditarOk.setPreferredSize(new java.awt.Dimension(136, 24));
        JaPanelCardEditarOk.setLayout(new java.awt.CardLayout());

        buttonEditarCliente.setBackground(new java.awt.Color(0, 154, 167));
        buttonEditarCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditarCliente.setText("Editar");
        buttonEditarCliente.setBorderPainted(false);
        buttonEditarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEditarCliente.setMaximumSize(new java.awt.Dimension(136, 24));
        buttonEditarCliente.setPreferredSize(new java.awt.Dimension(136, 24));
        buttonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarClienteActionPerformed(evt);
            }
        });
        JaPanelCardEditarOk.add(buttonEditarCliente, "card2");

        buttonOKEditarCliente.setBackground(new java.awt.Color(0, 166, 68));
        buttonOKEditarCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonOKEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        buttonOKEditarCliente.setText("OK");
        buttonOKEditarCliente.setBorderPainted(false);
        buttonOKEditarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonOKEditarCliente.setMaximumSize(new java.awt.Dimension(136, 24));
        buttonOKEditarCliente.setPreferredSize(new java.awt.Dimension(136, 24));
        buttonOKEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKEditarClienteActionPerformed(evt);
            }
        });
        JaPanelCardEditarOk.add(buttonOKEditarCliente, "card3");

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTableClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addComponent(titleClientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(containerInfoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JaPanelCardEditarOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonAnhadirCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(buttonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonEliminarCliente))))
                .addGap(20, 20, 20))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleClientes))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textFieldBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(containerInfoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(buttonAnhadirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JaPanelCardEditarOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonEliminarCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTableClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 79, 86));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(300, 175));

        contenedorApp.setPreferredSize(new java.awt.Dimension(950, 500));
        contenedorApp.setLayout(new java.awt.BorderLayout());

        leftPanel.setBackground(new java.awt.Color(0, 154, 167));
        leftPanel.setPreferredSize(new java.awt.Dimension(150, 500));

        buttonMenuClientes.setBackground(new java.awt.Color(0, 79, 86));
        buttonMenuClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonMenuClientes.setForeground(new java.awt.Color(255, 255, 255));
        buttonMenuClientes.setText("Clientes");
        buttonMenuClientes.setBorderPainted(false);
        buttonMenuClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMenuClientes.setPreferredSize(new java.awt.Dimension(130, 24));
        buttonMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuClientesActionPerformed(evt);
            }
        });

        buttonMenuReservas.setBackground(new java.awt.Color(0, 79, 86));
        buttonMenuReservas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonMenuReservas.setForeground(new java.awt.Color(255, 255, 255));
        buttonMenuReservas.setText("Reservas");
        buttonMenuReservas.setBorderPainted(false);
        buttonMenuReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMenuReservas.setPreferredSize(new java.awt.Dimension(130, 24));
        buttonMenuReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuReservasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GALICIA SECRETA");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                        .addComponent(buttonMenuClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                        .addComponent(buttonMenuReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(buttonMenuClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonMenuReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        contenedorApp.add(leftPanel, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMenuClientesActionPerformed

    private void buttonAnhadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnhadirClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAnhadirClienteActionPerformed

    private void buttonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarClienteActionPerformed

    private void buttonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditarClienteActionPerformed

    private void textFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmailActionPerformed

    private void textFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIDActionPerformed

    private void buttonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEliminarClienteActionPerformed

    private void textFieldBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscarClienteActionPerformed

    private void buttonOKEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKEditarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOKEditarClienteActionPerformed

    private void buttonMenuReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMenuReservasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JaPanelCardEditarOk;
    private javax.swing.JButton buttonAnhadirCliente;
    private javax.swing.JButton buttonBuscarCliente;
    private javax.swing.JButton buttonEditarCliente;
    private javax.swing.JButton buttonEliminarCliente;
    private javax.swing.JButton buttonMenuClientes;
    private javax.swing.JButton buttonMenuReservas;
    private javax.swing.JButton buttonOKEditarCliente;
    private javax.swing.JPanel containerInfoCliente;
    private javax.swing.JPanel contenedorApp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelDir;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTlf;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JScrollPane scrollTableClientes;
    protected javax.swing.JTable tableClientes;
    public javax.swing.JTextField textFieldApellidos;
    private javax.swing.JTextField textFieldBuscarCliente;
    public javax.swing.JTextField textFieldDir;
    public javax.swing.JTextField textFieldEmail;
    public javax.swing.JTextField textFieldID;
    public javax.swing.JTextField textFieldNombre;
    public javax.swing.JTextField textFieldTlf;
    private javax.swing.JLabel titleClientes;
    // End of variables declaration//GEN-END:variables
    
    // Métodos para añadir listeners a los botones de la interfaz de usuario
    
    /**
     * Añade un listener al botón clientes para cargar el panel clientes.
     * @param listener El listener a añadir.
     */
    public void addListenerMenuReservas(ActionListener listener) {
        buttonMenuReservas.addActionListener(listener);
    }
    
    /**
     * Añade un listener al botón para cargar el panel clientes.
     * @param listener El listener a añadir.
     */
    public void addMenuClientesListener(ActionListener listener) {
        buttonMenuClientes.addActionListener(listener);
    }    
    
    public void cargarCentro(JPanel panel) {
        if (panelActual != null) {
            contenedorApp.remove(panelActual);
        }
        if (panel != null) {
            contenedorApp.add(panel, BorderLayout.CENTER);
        }
        panelActual = panel; // Actualizamos panelActual
        contenedorApp.revalidate();
        contenedorApp.repaint();
    }
}
